nacos:
  config:
    server-addr: 10.8.228.106:8848,10.8.228.107:8848,10.8.228.108:8848
    auto-refresh: true # 是否开启自动刷新 ，对应的属性注解上也必须设置autoRefreshed = true才可以实时更新
    data-id: mall-oms
    namespace: rec
    username: nacos
    password: w6#H86a@@2
    type: yaml
    bootstrap:
      enable: true #开启配置预加载功能
      log-enable: true
    remote-first: true #远程优先，相同的key nacos 会覆盖本地配置。